import React,{useEffect,useState} from 'react';
import {ArrowRight,LogOut,Package,UserRound} from 'lucide-react';
import {useStore} from '../context/StoreContext';

export default function AccountPage({navigate}:{navigate:(p:string)=>void}){
 const {customer,orders,login,register,logout,refreshOrders}=useStore();
 const [tab,setTab]=useState<'login'|'register'>(customer?'login':'login');
 const [identifier,setIdentifier]=useState('');const [password,setPassword]=useState('');
 const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');
 const [loading,setLoading]=useState(false);
 useEffect(()=>{if(customer)void refreshOrders()},[customer]);
 if(customer)return <main className="min-h-screen bg-slate-50 py-8"><div className="max-w-6xl mx-auto px-4"><div className="bg-slate-950 text-white rounded-3xl p-6 sm:p-8 flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="text-xs font-black text-teal-300 uppercase tracking-widest">MY ACCOUNT</div><h1 className="text-3xl font-black mt-1">Hello, {customer.name}</h1><p className="text-slate-300 mt-1">{customer.phone}{customer.email?' · '+customer.email:''}</p></div><button onClick={()=>{logout();navigate('/')}} className="px-4 py-2.5 rounded-xl bg-white/10 font-black text-sm flex items-center gap-2"><LogOut className="w-4 h-4"/> Sign out</button></div><div className="grid lg:grid-cols-[1fr_300px] gap-5 mt-5"><section className="bg-white rounded-3xl border p-5"><h2 className="text-xl font-black flex items-center gap-2"><Package className="w-5 h-5"/> My Orders</h2>{orders.length===0?<div className="py-16 text-center text-slate-400">No orders yet. <button onClick={()=>navigate('/shop')} className="text-teal-700 font-bold">Start shopping</button></div>:<div className="mt-4 divide-y">{orders.map(o=><div key={o.id} className="py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><b>{o.order_number}</b><div className="text-xs text-slate-500 mt-1">{new Date(o.created_at).toLocaleString()} · {o.payment_method}</div><div className="text-xs mt-2">{(Array.isArray(o.items)?o.items:[]).map((i:any)=><span key={i.productId} className="inline-block mr-2 px-2 py-1 rounded-lg bg-slate-50">{i.name} × {i.quantity}</span>)}</div></div><div className="sm:text-right"><div className="font-black text-lg">৳{Number(o.total).toLocaleString()}</div><div className="text-xs font-black text-teal-700">{o.status}</div></div></div>)}</div>}</section><aside className="bg-white rounded-3xl border p-5 h-fit"><div className="w-12 h-12 rounded-2xl bg-teal-50 grid place-items-center text-teal-700"><UserRound/></div><h3 className="font-black mt-4">Account Details</h3><p className="text-sm text-slate-500 mt-1">Keep your phone and delivery information updated from your customer account.</p><button onClick={()=>navigate('/shop')} className="mt-5 w-full py-3 rounded-xl bg-slate-950 text-white font-black flex items-center justify-center gap-2">Continue Shopping <ArrowRight className="w-4 h-4"/></button></aside></div></div></main>;

 const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);try{if(tab==='login')await login(identifier,password);else await register({name,phone,email,password});const next=new URLSearchParams(window.location.search).get('next');navigate(next||'/account')}catch(err){alert((err as Error).message)}finally{setLoading(false)}};
 return <main className="min-h-screen bg-slate-50 py-10"><div className="max-w-md mx-auto px-4"><div className="bg-white rounded-3xl border shadow-sm p-6 sm:p-8"><div className="w-14 h-14 rounded-2xl bg-slate-950 text-white grid place-items-center mx-auto"><UserRound/></div><h1 className="text-2xl font-black text-center mt-4">{tab==='login'?'Welcome back':'Create your account'}</h1><p className="text-center text-sm text-slate-500 mt-1">{tab==='login'?'Sign in to order and track your purchases.':'Register once and checkout faster next time.'}</p><div className="grid grid-cols-2 gap-2 bg-slate-100 rounded-xl p-1 mt-6"><button onClick={()=>setTab('login')} className={'py-2 rounded-lg text-xs font-black '+(tab==='login'?'bg-white shadow':'text-slate-500')}>Sign In</button><button onClick={()=>setTab('register')} className={'py-2 rounded-lg text-xs font-black '+(tab==='register'?'bg-white shadow':'text-slate-500')}>Register</button></div><form onSubmit={submit} className="space-y-3 mt-5">{tab==='register'&&<><input value={name} onChange={e=>setName(e.target.value)} required placeholder="Full name" className="w-full rounded-xl border px-4 py-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} required placeholder="Phone number" className="w-full rounded-xl border px-4 py-3"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email (optional)" className="w-full rounded-xl border px-4 py-3"/></>}{tab==='login'&&<input value={identifier} onChange={e=>setIdentifier(e.target.value)} required placeholder="Phone or email" className="w-full rounded-xl border px-4 py-3"/>}<input value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} type="password" placeholder="Password (minimum 6 characters)" className="w-full rounded-xl border px-4 py-3"/><button disabled={loading} className="w-full py-3.5 rounded-2xl bg-slate-950 text-white font-black disabled:opacity-50">{loading?'Please wait…':tab==='login'?'Sign In':'Create Account'}</button></form><button onClick={()=>navigate('/shop')} className="w-full mt-4 py-2 text-sm text-slate-500">Continue as browsing customer</button></div></div></main>;
}
