import React,{useMemo,useState} from 'react';
import {ArrowRight,ChevronRight,Minus,Package,Plus,Search,ShoppingCart,Star,Trash2,Truck,Zap,Plane,Globe2,FileCheck,Calculator,ShieldCheck} from 'lucide-react';
import {useStore,Product} from '../context/StoreContext';

type Props={navigate:(p:string)=>void;mode:'home'|'shop'|'cart'|'checkout'};
const money=(n:number)=>'৳'+Number(n||0).toLocaleString('en-BD');

function ProductCard({p,navigate}:{p:Product;navigate:(p:string)=>void}){
 const {addToCart}=useStore();
 return <article className="group bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm hover:shadow-xl hover:-translate-y-0.5 transition-all">
  <div className="aspect-[5/3] bg-gradient-to-br from-slate-100 to-teal-50 relative overflow-hidden">
   {p.image_url?<img src={p.image_url} alt={p.name} className="w-full h-full object-cover group-hover:scale-105 transition-transform"/>:<div className="w-full h-full grid place-items-center text-teal-300"><Package className="w-12 h-12"/></div>}
   {p.featured&&<span className="absolute top-3 left-3 bg-red-600 text-white text-[10px] font-black px-2.5 py-1 rounded-full">POPULAR</span>}
  </div>
  <div className="p-4"><div className="text-[10px] font-black uppercase tracking-widest text-teal-700">{p.category||'Service'}</div><h3 className="font-black mt-1 line-clamp-2">{p.name}</h3><p className="text-xs text-slate-500 mt-1 line-clamp-2 min-h-8">{p.description||'SIAM AIR & DIGITAL SERVICE'}</p><div className="flex items-end justify-between gap-2 mt-4"><div><div className="text-xl font-black">{money(Number(p.price))}</div>{p.compare_price&&<div className="text-xs text-slate-400 line-through">{money(Number(p.compare_price))}</div>}</div><button onClick={()=>{addToCart(p);navigate('/cart')}} className="px-3 py-2.5 rounded-xl bg-slate-950 text-white text-xs font-black">Order</button></div></div>
 </article>;
}

function CartPage({navigate}:{navigate:(p:string)=>void}){
 const {cart,removeFromCart,setQty,customer,settings}=useStore(); const subtotal=cart.reduce((n,i)=>n+Number(i.product.price)*i.quantity,0); const delivery=subtotal>=Number(settings.freeDeliveryMinimum||0)?0:Number(settings.deliveryFee||0); const total=subtotal+delivery;
 return <main className="min-h-screen bg-slate-50 py-8"><div className="max-w-6xl mx-auto px-4"><button onClick={()=>navigate('/shop')} className="text-sm font-bold text-slate-500 mb-5">← Continue shopping</button><div className="grid lg:grid-cols-[1fr_360px] gap-5"><section className="bg-white rounded-2xl border p-5"><h1 className="text-2xl font-black">Your Service Cart</h1>{!cart.length?<div className="py-20 text-center text-slate-400">No services selected.</div>:<div className="divide-y">{cart.map(i=><div key={i.product.id} className="py-4 flex gap-3"><div className="w-20 h-20 rounded-xl bg-slate-100 overflow-hidden">{i.product.image_url&&<img src={i.product.image_url} className="w-full h-full object-cover"/></div><div className="flex-1"><b>{i.product.name}</b><div className="text-sm text-slate-500">{money(Number(i.product.price))}</div><div className="flex items-center gap-2 mt-2"><button onClick={()=>setQty(i.product.id,i.quantity-1)} className="p-1.5 rounded-lg bg-slate-100"><Minus className="w-4 h-4"/></button><span className="w-8 text-center font-black">{i.quantity}</span><button onClick={()=>setQty(i.product.id,i.quantity+1)} className="p-1.5 rounded-lg bg-slate-100"><Plus className="w-4 h-4"/></button><button onClick={()=>removeFromCart(i.product.id)} className="ml-2 p-1.5 text-rose-600"><Trash2 className="w-4 h-4"/></button></div></div><b>{money(Number(i.product.price)*i.quantity)}</b></div>)}</div>}</section><aside className="bg-white rounded-2xl border p-5 h-fit"><h2 className="font-black">Order Summary</h2><div className="flex justify-between mt-5 text-sm"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="flex justify-between mt-2 text-sm"><span>Service / Delivery</span><b>{delivery?money(delivery):'FREE'}</b></div><div className="border-t mt-4 pt-4 flex justify-between text-lg"><b>Total</b><b>{money(total)}</b></div><button disabled={!cart.length} onClick={()=>navigate(customer?'/checkout':'/account?next=/checkout')} className="w-full mt-5 py-3.5 rounded-xl bg-teal-700 text-white font-black disabled:opacity-40">{customer?'Continue':'Sign in to continue'}</button></aside></div></div></main>;
}

function CheckoutPage({navigate}:{navigate:(p:string)=>void}){
 const {cart,customer,settings,checkout,notice}=useStore(); const [address,setAddress]=useState(customer?.address||'');const [city,setCity]=useState(customer?.city||'');const [payment,setPayment]=useState('cod');const [note,setNote]=useState(''); const subtotal=cart.reduce((n,i)=>n+Number(i.product.price)*i.quantity,0);const delivery=subtotal>=Number(settings.freeDeliveryMinimum||0)?0:Number(settings.deliveryFee||0);const total=subtotal+delivery;
 const place=async()=>{try{const o=await checkout({address,city,paymentMethod:payment,note});notice('Order '+o.order_number+' received');navigate('/account')}catch(e){alert((e as Error).message)}}; if(!customer)return <main className="min-h-screen grid place-items-center"><button onClick={()=>navigate('/account?next=/checkout')} className="px-5 py-3 rounded-xl bg-slate-950 text-white font-bold">Sign In</button></main>;
 return <main className="min-h-screen bg-slate-50 py-8"><div className="max-w-5xl mx-auto px-4"><h1 className="text-3xl font-black">Confirm Service Request</h1><p className="text-slate-500 mt-1">Order as {customer.name}</p><div className="grid lg:grid-cols-[1fr_360px] gap-5 mt-6"><section className="bg-white rounded-2xl border p-5 space-y-4"><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Full address" className="w-full rounded-xl border px-4 py-3"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City / Area" className="w-full rounded-xl border px-4 py-3"/><select value={payment} onChange={e=>setPayment(e.target.value)} className="w-full rounded-xl border px-4 py-3"><option value="cod">Pay at office / confirmation</option>{settings.bkashEnabled&&<option value="bkash">bKash</option>}{settings.nagadEnabled&&<option value="nagad">Nagad</option>}{settings.bankEnabled&&<option value="bank">Bank Transfer</option>}</select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Passenger / service note" className="w-full rounded-xl border px-4 py-3 min-h-28"/><button onClick={place} className="w-full py-4 rounded-xl bg-teal-700 text-white font-black">Submit Request · {money(total)}</button></section><aside className="bg-white rounded-2xl border p-5 h-fit"><h2 className="font-black">Selected Services</h2>{cart.map(i=><div key={i.product.id} className="flex justify-between gap-3 py-3 border-b text-sm"><span>{i.product.name} × {i.quantity}</span><b>{money(Number(i.product.price)*i.quantity)}</b></div>)}<div className="flex justify-between pt-4"><b>Total</b><b className="text-xl">{money(total)}</b></div></aside></div></div></main>;
}

const QuickTile=({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void})=><button onClick={onClick} className="text-left bg-white rounded-2xl border border-slate-200 p-4 hover:border-teal-400 hover:shadow-md transition"><div className="w-10 h-10 rounded-xl bg-teal-50 text-teal-700 grid place-items-center">{icon}</div><b className="block mt-3">{title}</b><span className="text-xs text-slate-500">{text}</span></button>;

export default function StorefrontPage({navigate,mode}:Props){
 const {identity,settings,products}=useStore(); const [search,setSearch]=useState('');const [category,setCategory]=useState('all');
 const cats=useMemo(()=>['all',...Array.from(new Set(products.map(p=>p.category).filter(Boolean) as string[]))],[products]);
 const filtered=useMemo(()=>products.filter(p=>(category==='all'||p.category===category)&&(!search||p.name.toLowerCase().includes(search.toLowerCase())||String(p.category||'').toLowerCase().includes(search.toLowerCase()))),[products,category,search]);
 if(mode==='cart')return <CartPage navigate={navigate}/>; if(mode==='checkout')return <CheckoutPage navigate={navigate}/>;
 return <main className="bg-slate-50">
  {mode==='home'&&<><section className="relative overflow-hidden bg-gradient-to-br from-slate-950 via-teal-950 to-red-950 text-white"><div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_15%_20%,#2dd4bf,transparent_30%),radial-gradient(circle_at_85%_80%,#ef4444,transparent_25%)]"/><div className="relative max-w-7xl mx-auto px-4 py-10 sm:py-16"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/10 border border-white/10 text-teal-200 text-xs font-black"><Zap className="w-3.5 h-3.5"/> {settings.announcement||'Travel & Digital Service Marketplace'}</div><h1 className="text-4xl sm:text-6xl font-black leading-[1.05] mt-5">Travel, visa & digital services — <span className="text-teal-300">all in one place.</span></h1><p className="text-slate-300 text-base sm:text-lg mt-5 max-w-2xl">Compare services, send booking requests, upload documents and track your requests with SIAM AIR AND DIGITAL SERVICE.</p><div className="mt-7 bg-white rounded-2xl p-2 shadow-2xl max-w-3xl"><div className="grid grid-cols-2 sm:grid-cols-4 gap-1">{[['Flight','/shop'],['Visa','/shop'],['Services','/shop'],['Tools','/tools']].map(([t,p])=><button key={t} onClick={()=>navigate(p)} className="rounded-xl px-3 py-3 text-sm font-black text-slate-800 hover:bg-teal-50">{t}</button>)}</div><div className="relative mt-2"><Search className="absolute left-4 top-3.5 w-5 h-5 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&navigate('/shop?search='+encodeURIComponent(search))} placeholder="Search air ticket, visa, passport, police clearance..." className="w-full rounded-xl bg-slate-100 py-3 pl-11 pr-4 text-sm outline-none"/></div></div></div></div></section>
  <section className="max-w-7xl mx-auto px-4 -mt-7 relative z-10 grid grid-cols-2 lg:grid-cols-4 gap-3"><QuickTile icon={<Plane/>} title="Air Ticket" text="Flight quotation & booking" onClick={()=>navigate('/shop')}/><QuickTile icon={<Globe2/>} title="Visa Services" text="India, Saudi, Thailand & more" onClick={()=>navigate('/shop')}/><QuickTile icon={<FileCheck/>} title="Document Services" text="Passport, PCC, medical & more" onClick={()=>navigate('/shop')}/><QuickTile icon={<Calculator/>} title="Ticketing Tools" text="PNR & Net Fare Calculator" onClick={()=>navigate('/tools')}/></section>
  <section className="max-w-7xl mx-auto px-4 py-12"><div className="flex items-end justify-between"><div><div className="text-xs font-black text-teal-700 uppercase tracking-[.18em]">Popular services</div><h2 className="text-3xl font-black mt-1">Book a service online</h2></div><button onClick={()=>navigate('/shop')} className="text-sm font-black text-teal-700 flex items-center">View all <ChevronRight className="w-4 h-4"/></button></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-6">{filtered.slice(0,8).map(p=><ProductCard key={p.id} p={p} navigate={navigate}/>)}</div></section>
  <section className="bg-white border-y"><div className="max-w-7xl mx-auto px-4 py-10"><div className="grid md:grid-cols-3 gap-4"><div className="rounded-2xl bg-slate-50 p-5"><ShieldCheck className="text-teal-700"/><b className="block mt-3">Verified service desk</b><span className="text-xs text-slate-500">Real customer request flow with order records.</span></div><div className="rounded-2xl bg-slate-50 p-5"><Truck className="text-teal-700"/><b className="block mt-3">Human support</b><span className="text-xs text-slate-500">WhatsApp, phone and office support for every request.</span></div><div className="rounded-2xl bg-slate-50 p-5"><Star className="text-amber-500"/><b className="block mt-3">One agency, many services</b><span className="text-xs text-slate-500">Ticketing, visa and digital services under one brand.</span></div></div></div></section></>}
  {mode==='shop'&&<section className="max-w-7xl mx-auto px-4 py-8 sm:py-12"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><div className="text-xs font-black text-teal-700 uppercase tracking-widest">SERVICE CATALOG</div><h1 className="text-3xl sm:text-4xl font-black">Travel & Digital Services</h1></div><div className="relative w-full md:w-96"><Search className="absolute left-3 top-3.5 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search services..." className="w-full rounded-xl border bg-white py-3 pl-10 pr-4"/></div></div><div className="flex gap-2 overflow-x-auto mt-5 pb-1">{cats.map(c=><button key={c} onClick={()=>setCategory(c)} className={'px-4 py-2 rounded-xl text-xs font-black whitespace-nowrap '+(category===c?'bg-slate-950 text-white':'bg-white border')}>{c==='all'?'All services':c}</button>)}</div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-6">{filtered.map(p=><ProductCard key={p.id} p={p} navigate={navigate}/>)}</div>{!filtered.length&&<div className="py-20 text-center text-slate-400">No matching service found.</div>}</section>}
 </main>;
}