import React,{useState} from 'react';
import {Menu,Search,ShoppingCart,UserRound,X,Phone,MessageCircle} from 'lucide-react';
import {StoreProvider,useStore} from './context/StoreContext';
import StorefrontPage from './pages/StorefrontPage';
import AccountPage from './pages/AccountPage';
import ToolsPage from './pages/ToolsPage';
import FlightQuotePage from './pages/FlightQuotePage';

const Header=({navigate,path}:{navigate:(p:string)=>void;path:string})=>{
 const {identity,cart,customer}=useStore();const [open,setOpen]=useState(false);const [search,setSearch]=useState('');
 const go=(p:string)=>{setOpen(false);navigate(p)};
 return <header className="sticky top-0 z-50 bg-white/95 backdrop-blur border-b border-slate-200"><div className="max-w-7xl mx-auto px-4 h-16 flex items-center gap-3">
  <button className="lg:hidden p-2 rounded-xl bg-slate-100" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>
  <button onClick={()=>go('/')} className="flex items-center gap-2 min-w-0"><div className="w-10 h-10 rounded-xl bg-sky-700 overflow-hidden grid place-items-center">{identity.logoUrl?<img src={identity.logoUrl} className="w-full h-full object-contain"/>:<span className="text-white font-black">SA</span>}</div><div className="hidden sm:block text-left"><div className="font-black leading-none truncate max-w-[190px]">{identity.name}</div><div className="text-[10px] text-slate-500 mt-1 truncate max-w-[190px]">{identity.tagline}</div></div></button>
  <nav className="hidden lg:flex items-center gap-5 ml-5 text-sm font-bold"><button onClick={()=>go('/')} className={path==='/'?'text-sky-700':''}>Home</button><button onClick={()=>go('/shop')} className={path==='/shop'?'text-sky-700':''}>Services</button><button onClick={()=>go('/account')} className={path==='/account'?'text-sky-700':''}>My Orders</button><button onClick={()=>go('/tools')} className={path==='/tools'?'text-sky-700':''}>Ticketing Tools</button><button onClick={()=>go('/flights')} className={path==='/flights'?'text-sky-700':''}>Flights & Hotels</button></nav>
  <div className="hidden md:flex flex-1 max-w-md ml-auto relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go('/shop?search='+encodeURIComponent(search))} placeholder="Search flights, visa & services" className="w-full rounded-xl bg-slate-100 py-2 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-sky-100"/></div>
  <button onClick={()=>go('/account')} className="p-2 rounded-xl hover:bg-slate-100 relative" title={customer?'My Account':'Sign In'}><UserRound className="w-5 h-5"/>{customer&&<span className="absolute top-1 right-1 w-2 h-2 bg-emerald-500 rounded-full"/>}</button>
  <button onClick={()=>go('/cart')} className="p-2 rounded-xl hover:bg-slate-100 relative"><ShoppingCart className="w-5 h-5"/>{cart.length>0&&<span className="absolute -top-1 -right-1 min-w-5 h-5 px-1 rounded-full bg-rose-600 text-white text-[10px] font-black grid place-items-center">{cart.reduce((n,i)=>n+i.quantity,0)}</span>}</button>
 </div>{open&&<div className="lg:hidden border-t bg-white p-4 space-y-2"><button onClick={()=>go('/')} className="block w-full text-left p-3 rounded-xl font-bold">Home</button><button onClick={()=>go('/shop')} className="block w-full text-left p-3 rounded-xl font-bold">Shop</button><button onClick={()=>go('/account')} className="block w-full text-left p-3 rounded-xl font-bold">My Account / Orders</button><button onClick={()=>go('/flights')} className="block w-full text-left p-3 rounded-xl font-bold">Flights & Hotels</button><button onClick={()=>go('/tools')} className="block w-full text-left p-3 rounded-xl font-bold">PNR & Fare Tools</button><div className="flex gap-2 pt-2"><a href={'tel:'+identity.mobile} className="flex-1 p-3 rounded-xl bg-slate-100 text-center"><Phone className="w-4 h-4 inline mr-1"/>Call</a><a href={'https://wa.me/'+String(identity.whatsapp||identity.mobile).replace(/[^0-9]/g,'')} className="flex-1 p-3 rounded-xl bg-emerald-50 text-emerald-700 text-center"><MessageCircle className="w-4 h-4 inline mr-1"/>WhatsApp</a></div></div>}</header>;
};

const Footer=({navigate}:{navigate:(p:string)=>void})=>{const {identity}=useStore();return <footer className="bg-slate-950 text-slate-300 mt-10"><div className="max-w-7xl mx-auto px-4 py-10 grid md:grid-cols-4 gap-8"><div className="md:col-span-2"><div className="text-white font-black text-xl">{identity.name}</div><p className="text-sm mt-2 max-w-xl">{identity.tagline||'Air Ticket · Visa Processing · Passport & Digital Solutions'}</p><p className="text-xs text-slate-500 mt-4">{identity.address}</p></div><div><b className="text-white">Store</b><button onClick={()=>navigate('/shop')} className="block mt-3 text-sm">Shop</button><button onClick={()=>navigate('/account')} className="block mt-2 text-sm">My Account</button><button onClick={()=>navigate('/cart')} className="block mt-2 text-sm">Cart</button></div><div><b className="text-white">Contact</b><p className="text-sm mt-3">{identity.mobile}</p><p className="text-sm mt-2">{identity.email}</p></div></div><div className="border-t border-white/10 py-4 text-center text-xs text-slate-500">© {new Date().getFullYear()} {identity.name}. All rights reserved.</div></footer>};

function AppContent(){
 const [path,setPath]=useState(window.location.pathname||'/');
 const navigate=(p:string)=>{const clean=p.split('?')[0]||'/';window.history.pushState({},'',p);setPath(clean);window.scrollTo({top:0,behavior:'smooth'})};
 React.useEffect(()=>{const h=()=>setPath(window.location.pathname||'/');window.addEventListener('popstate',h);return()=>window.removeEventListener('popstate',h)},[]);
 const render=()=>{if(path==='/account')return <AccountPage navigate={navigate}/>;if(path==='/flights')return <FlightQuotePage/>;if(path==='/tools')return <ToolsPage/>;if(path==='/cart')return <StorefrontPage navigate={navigate} mode="cart"/>;if(path==='/checkout')return <StorefrontPage navigate={navigate} mode="checkout"/>;if(path==='/shop')return <StorefrontPage navigate={navigate} mode="shop"/>;return <StorefrontPage navigate={navigate} mode="home"/>};
 return <div className="min-h-screen bg-slate-50 text-slate-900"><Header navigate={navigate} path={path}/>{render()}<Footer navigate={navigate}/></div>;
}
export default function App(){return <StoreProvider><AppContent/></StoreProvider>;}
